name: check ip
on: workflow_dispatch
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -s https://ipinfo.io/json
          echo "---"
          curl -s https://ifconfig.me
          echo "---"
          curl -s https://api.ipify.org
